-- packer
require("plugins.plugins-setup")
require("core.options")
require("core.keymaps")
require("core.autocmds")

-- 引用插件 , 修改插件快捷键到keymaps.lua中修改,或对应的插件文件中配置
require("plugins.ui.colorscheme")
require("plugins.ui.lualine")
require("plugins.utils.nvim-tree")
require("plugins.code.treesitter")
require("plugins.code.lsp")
require("plugins.code.cmp")
require("plugins.code.comment")
require("plugins.code.autopairs")
require("plugins.ui.bufferline")
require("plugins.ui.gitsigns")
require("plugins.utils.telescope")
require("plugins.utils.which-key")
require("plugins.utils.mini-bufremove")
require("plugins.code.conform")
require("plugins.ui.alpha-nvim")
require("plugins.ui.persisted")
require("plugins.utils.leap")
require("plugins.utils.toggleterm")
require("plugins.utils.lazygit")
require("plugins.utils.typescript-tools")
